/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appjardiniot.GUIs;

import appjardiniot.Clases.SistRiego;
import appjardiniot.Clases.Usuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import javax.swing.ImageIcon;

/**
 *
 * @author Rodrigo S
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }
    
    public Login(SistRiego SR) {    //Constructor2, para ser llamado se debe crear un objeto instanciado con un objeto SistRiego
        this.SR = SR;               //Se iguala el objeto creado aqui en la clase con el instanciado
        Leer();                     //Lee y carga los datos del archivo mandando a llamar al metodo
        Users = getUsers();         //Guarda lo creado en el metodo
        initComponents();           
        setIconImage(new ImageIcon(getClass().getResource("/appjardiniot/Images/Icon5.png")).getImage());       //Pone el incono
        this.getContentPane().setBackground(new Color(220,196,244));                                            //Colorea el Frame
        jPanel2.setBackground(new Color(220,196,244));                                                          //Colorea el jpanel
        //166,216,223
        //191,171,203
        //[227,206,246]
        Verificar(Var);           //Llama la metodo con el parametro de 0
    }
       
    public void Verificar(int Option){      //Este metodo revisa la cantidad de usuarios en el objeto SistRiego, si es 0
        String NombreUsers[];               // no puede iniciar sesion, caso contrario muestra los nombres guardados en el arreglo
        if(Users.length == 0){
            InSesion.setEnabled(false);
       }else{                       //Todo lo comentado son cosas que no funcionan
            int i;
            //Leer();
            User = SR.getUser(Option);     
            //System.out.println(User);
            //Var = Option; 
            System.out.println(Var);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TNombre = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        TContra = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        Registrarse = new javax.swing.JButton();
        InSesion = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Riego Alpha 0.001");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImages(null);
        setPreferredSize(new java.awt.Dimension(610, 510));
        setResizable(false);

        jPanel2.setMaximumSize(new java.awt.Dimension(600, 600));
        jPanel2.setMinimumSize(new java.awt.Dimension(600, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(600, 600));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appjardiniot/Images/Login1.png"))); // NOI18N
        jPanel2.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de Usuario:");

        TNombre.setBackground(new java.awt.Color(237, 225, 249));
        TNombre.setModel(new javax.swing.DefaultComboBoxModel<>(Users)

        );
        TNombre.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TNombreItemStateChanged(evt);
            }
        });
        TNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TNombreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Contraseña:");

        TContra.setBackground(new java.awt.Color(237, 225, 249));
        TContra.setMaximumSize(new java.awt.Dimension(30, 400));

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        Registrarse.setBackground(new java.awt.Color(237, 225, 249));
        Registrarse.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Registrarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appjardiniot/Images/Register.png"))); // NOI18N
        Registrarse.setText("Registrarse");
        Registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarseActionPerformed(evt);
            }
        });
        jPanel1.add(Registrarse);

        InSesion.setBackground(new java.awt.Color(237, 225, 249));
        InSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        InSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appjardiniot/Images/join.png"))); // NOI18N
        InSesion.setText("Iniciar Sesión");
        InSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InSesionActionPerformed(evt);
            }
        });
        jPanel1.add(InSesion);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/appjardiniot/Images/Password.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TNombre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TContra, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TContra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarseActionPerformed
        //Al presionar el boton pasa la informacion de login a Registro, sin ella es imposible guarfar la información
        Registro Ven;
        Ven = new Registro();
        Ven.setSR(SR);
        Ven.setLogin(this);
        Ven.setVisible(true);
        //setVisible(false);
        dispose();
    }//GEN-LAST:event_RegistrarseActionPerformed

    private void InSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InSesionActionPerformed
        //Si la contraseña coincide pasa la informacion de login a MenuPrincipal
        if(TContra.getText().equalsIgnoreCase(SR.getUser(Var).getPassword())){
            MenuPrincipal MP;
            MP = new MenuPrincipal(SR, User, Var);
            //MP.setSR(SR);
            MP.setLogin(this);
            MP.setUser(User);
            MP.setVisible(true);
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta", "Error",JOptionPane.ERROR_MESSAGE+JOptionPane.YES_NO_OPTION,null);
        }
    }//GEN-LAST:event_InSesionActionPerformed

    private void TNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TNombreActionPerformed

    private void TNombreItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TNombreItemStateChanged
        Verificar(TNombre.getSelectedIndex());
        Var = TNombre.getSelectedIndex();
    }//GEN-LAST:event_TNombreItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InSesion;
    private javax.swing.JButton Registrarse;
    private javax.swing.JPasswordField TContra;
    private javax.swing.JComboBox<String> TNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    SistRiego SR;
    String Users[];
    Usuario User;
    MenuPrincipal menu;
    int Var;
    
    public String[] getUsers(){     //Este metodo crea un arreglo con el numero de espacios igual al num de usuarios y los asigna en cada espacio.
        int i;
        String Users[];
        Users = new String[SR.getNumUsers()];
        for(i=0;i<Users.length;i++){
            Users[i] = SR.getUser(i).getNombre();
        }
        return Users;
    }
    
    public void setSR(SistRiego sr){    //Este metodo guarda la información de la clase SistRiego
        SR = sr;
    }
  
    public void Leer(){    //Este metodo intenta leer el archivo de los usuarios creados
        ObjectInputStream In;
        try{
            In = new ObjectInputStream(new FileInputStream("Users.data"));
            SR = (SistRiego)In.readObject();        
            In.close();
            System.out.println("Archivo Cargado");

        }catch(FileNotFoundException e){
                    System.out.println("Archivo No Encontrado");                   
            }catch(IOException e){
                    System.out.println("No se puede Mostrar");                   
            } catch (ClassNotFoundException ex) {
                    System.out.println("Clase Erronea");                
            }  
    }

}
